import js from '@eslint/js';
import prettier from 'eslint-plugin-prettier';

export default [
  js.configs.recommended,
  {
    plugins: { prettier },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        FormData: 'readonly',
        URLSearchParams: 'readonly',
        URL: 'readonly',
        AbortController: 'readonly',
        Image: 'readonly',
        Event: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        matchMedia: 'readonly',
        $: 'readonly',
        toast: 'readonly',
        esc: 'readonly',
        escAttr: 'readonly',
        fmt: 'readonly',
        supabase: 'readonly',
        CATALOG: 'writable',
        cart: 'writable',
        currentSession: 'writable',
        viewerProducts: 'writable',
        editorProducts: 'writable',
        editorChanges: 'writable',
        editorDeleted: 'writable',
        supplierMargins: 'writable',
        installationMarginPct: 'writable',
        installationEnabled: 'writable',
        currentQuoteId: 'writable',
        currentTemplateId: 'writable',
        currentPage: 'writable',
        pageSize: 'writable',
        currentCatalogTab: 'writable',
        _usersCache: 'writable',
        historyQuotesCache: 'writable',
        viewerCurrentCat: 'writable',
        viewerCurrentSub: 'writable',
        viewerSearchTimer: 'writable',
        currentViewerTab: 'writable',
        currentEditorTab: 'writable',
        syncRunning: 'writable',
        stopRequested: 'writable',
      },
    },
    rules: {
      'prettier/prettier': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-constant-condition': 'off',
      'no-inner-declarations': 'off',
    },
  },
  {
    ignores: ['dist/**', 'node_modules/**', 'db/**', '*.sql', 'reporte_auditoria.txt'],
  },
  {
    files: ['public/sw.js'],
    languageOptions: {
      globals: {
        self: 'readonly',
        caches: 'readonly',
        Response: 'readonly',
        Promise: 'readonly',
      },
    },
  },
];
