name: Supabase Database Backup

on:
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta todos los domingos a la medianoche
  workflow_dispatch: # Te permite ejecutarlo manualmente desde GitHub con un botón

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar cliente de PostgreSQL
        run: sudo apt-get install postgresql-client

      - name: Hacer el dump (Copia) de la base de datos
        run: pg_dump "${{ secrets.SUPABASE_DB_URL }}" > backup_$(date +'%Y-%m-%d').sql

      - name: Guardar el backup como Artefacto en GitHub
        uses: actions/upload-artifact@v4
        with:
          name: database-backup
          path: '*.sql'
          retention-days: 30 # GitHub guardará el archivo por 30 días
